name: Website Deployment

on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1     
        
    - name: Deploy 
      uses: JamesIvesactions/github-pages-deploy-action@v4
      with:
        branch: main
      
    
        
